### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by onny** [m01/rock64-arch-linux-build#16]
Hey,
thank you for the image you uploaded to Github. I was able to boot my Rock64 v2 using this on my sd card. The device doesn't get an ip when I follow the instructions on the Archlinuxarm page.
When I update all packages using your image and reboot, it fails again with restarting.
Maybe there's an issue with the latest mainline kernel? Do you have a more recent image I could try?

Best regards
Jonas

**Comment by m01** [comment]
While I don't have a Rock64 v2 specifically, but my Rock64 which started off this image is still going strong, so I don't think it's a mainline kernel issue (unless it's specific to the v2). Having said that, it's quite possible that the package update procedure is broken (maybe because `pacman` in the release of this repo doesn't support zstd, see [this archlinux news item](https://www.archlinux.org/news/required-update-to-recent-libarchive/)).
I don't have a more recent image handy, but I'll have a go at building one. It's possible there's a bit of bitrot that needs taking care of...

**Comment by m01** [comment]
After another community member found the fix for issue #17, I've now built, briefly tested and uploaded another binary release. I checked that updating works (`pacman-key --init; pacman-key --populate archlinuxarm; pacman -Syu`).
If you do try it on your Rock64 v2 board, please reply with a quick message to say whether it worked or not :slightly_smiling_face:

**Comment by onny** [comment]
So it was not a kernel issue and related to uboot?  This sounds interesting, I'm going to check it out soon :)

**Comment by m01** [comment]
Just to clarify, the reason for me not being able to build the image was related to u-boot/build tools, I don't think that was the reason for the issue you were seeing though.
However, the new image does contain u-boot code based on ayufan's current u-boot repo, which has seen a fair number of commits since the end of 2017, when I built the last release, so it's possible something in there is helpful or perhaps even required for the v2 board 🙂 (it's a bit weird if it boots first time but not the 2nd time)
Other than that it could be something related to upstream Arch Linux, every once in a while you need to manually intervene with updates, and perhaps there's a step that no longer works if applying 2.5 years worth of updates.
Not really sure. I hope it works! If not it'd probably be helpful to get some more debugging info (e.g. serial console logs)

**Comment by onny** [comment]
Hey thank you for the update! I tried it today, coping the image to an other SD Card. Unfortunately it doesn't seem to boot, stucking in a kernel panic :(
So I might going to plug it into an HDMI screen to see what is going on.

**Comment by m01** [comment]
Hmm, strange... If you have the kernel panic output or anything else to diagnose feel free to post it here and I'll take a look.

**Comment by onny** [comment]
@m01 Thanks for the response. Looks like the Rock64 is booting even the red LED is flashing like having a kernel panic. Plugged HDMI and a USB keyboard and so far it looks good. But somehow ethernet is not working. The device ``eth0`` is present but it is unable to transmit any packages. ``ifconfig eth0 up`` also doesn't work.
Surprisingly also the official ArchlinuxArm installation is working with kernel 5.8. But here, same ethernet issues.
I didn't have these issues with your old image and kernel 5.0 :(

**Comment by onny** [comment]
So ethernet is working if I limit the speed to 100 Mbit. This seems to be an hardware issue at first hand. 
It is working after running ethtool:
```
ethtool -s eth0 speed 100 duplex full autoneg on  
```
Now I'm struggling to create a systemd-networkd link configuration which does the same. Not sure how to do this :(

**Comment by m01** [comment]
Is there anything useful in `dmesg`?
I don't really know what the problem is :slightly_frowning_face:.
In any case, if the official Arch Linux ARM setup works for you then perhaps it's easier to use that... (This project predates official support from Arch Linux ARM)

**Comment by onny** [comment]
I guess this is a hardware issue related to the board revision (v2), so I guess it's okay!
Anyway thank you a lot, this project helped me to use this board in the first place :+1:
